embedded config

diff --git a/.github/actions/trivy-triage/action.yaml b/.github/actions/trivy-triage/action.yaml
--- a/.github/actions/trivy-triage/action.yaml
+++ b/.github/actions/trivy-triage/action.yaml
@@ -1,13 +1,15 @@
 name: 'trivy-discussion-triage'
 description: 'automatic triage of Trivy discussions'
-inputs:
-  config-discussion-labels:
-    description: 'path to config file for matching discussion topics to labels'
 runs:
   using: "composite"
   steps:
     - run: |
         echo '${{ toJson(github.event.discussion) }}' > ./discussion-created.json
-        ${{ github.action_path }}/discussion-created.sh ./discussion-created.json
+        config_discussion_labels=$(echo '${{ github.action_labels }}/config-discussion-labels')
+        if ! [ -f "$config_discussion_labels" ]; then
+          echo "invalid discussion labels config file"
+          exit 1
+        fi
+        ${{ github.action_path }}/discussion-created.sh "./discussion-created.json" "$config_discussion_labels"
       if: ${{ github.event_name == 'discussion' && github.event.action == 'created' }}
       shell: bash
